spring.application.name=eventsync

# Database Settings
spring.datasource.url=jdbc:h2:mem:eventsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true


huggingface.api.url=https://router.huggingface.co/models/distilbert-base-uncased-finetuned-sst-2-english

huggingface.api.token=hf_YOUR_ACTUAL_TOKEN_HERE